import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {flexRender,getCoreRowModel,getSortedRowModel,useReactTable,type ColumnDef, type SortingState} from '@tanstack/react-table';
import {ExternalLink,Instagram,Facebook,Linkedin,Search,ChevronLeft,ChevronRight} from 'lucide-react';
import './styles.css';
import {registerStarkWebMCP} from './webmcp/register-tools';

type Lead={place_identity:string;place_name?:string;observed_category?:string;total_score?:number|string;reviews_count?:number|string;address?:string;phone_raw?:string;whatsapp?:string;website?:string;google_maps_url?:string;instagram?:string[];facebook?:string[];linkedin?:string[];emails?:string[];public_stage?:string;qualification_status?:string};
type Page={items:Lead[];page:number;page_size:number;total_items:number;total_pages:number;has_previous:boolean;has_next:boolean};
const empty:Page={items:[],page:1,page_size:25,total_items:0,total_pages:0,has_previous:false,has_next:false};
const text=(v:any)=>v===null||v===undefined||v===''?'—':String(v);
function pageItems(current:number,total:number){if(total<=7)return Array.from({length:total},(_,i)=>i+1) as (number|string)[];const a:(number|string)[]=[1];if(current>4)a.push('…');for(let n=Math.max(2,current-1);n<=Math.min(total-1,current+1);n++)a.push(n);if(current<total-3)a.push('…');a.push(total);return a.filter((x,i,a)=>i===0||x!==a[i-1]);}
function Link({href,label}:any){return href?<a href={href} target="_blank" rel="noreferrer noopener">{label}<ExternalLink size={13}/></a>:<span>—</span>}
function App(){useEffect(()=>registerStarkWebMCP(),[]);const [category,setCategory]=useState('lanchonete'),[city,setCity]=useState('Campo Grande'),[state,setState]=useState('Mato Grosso do Sul'),[max,setMax]=useState('20'),[all,setAll]=useState(false),[save,setSave]=useState(false),[job,setJob]=useState(''),[page,setPage]=useState(empty),[pageNo,setPageNo]=useState(1),[query,setQuery]=useState(''),[sorting,setSorting]=useState<SortingState>([]),[status,setStatus]=useState('Antes da busca'),[busy,setBusy]=useState(false);
 const load=async(p=pageNo)=>{if(!job)return;try{const jr=await fetch('/api/v2/jobs/'+job);if(jr.ok){const j=await jr.json();const map:any={queued:'Buscando empresas...',running:'Coletando informações...',partial:'A busca encontrou parte dos resultados.',error:'Não foi possível concluir a busca.',completed:j.event_count?'Busca concluída.':'Nenhuma empresa encontrada para esta busca.',cancelled:'Busca cancelada'};if(map[j.status])setStatus(map[j.status])}const u=new URL('/api/v2/jobs/'+job+'/places',location.origin);u.searchParams.set('page',String(p));u.searchParams.set('page_size','25');if(query)u.searchParams.set('q',query);if(sorting[0]){u.searchParams.set('sort',sorting[0].id);u.searchParams.set('order',sorting[0].desc?'desc':'asc')}const r=await fetch(u);if(r.ok)setPage(await r.json())}catch{setStatus('A conexão foi interrompida. Tentando reconectar...')}};
 useEffect(()=>{if(!job)return;const t=setInterval(()=>load(pageNo),1500);return()=>clearInterval(t)},[job,pageNo,query,sorting]);
 const start=async()=>{setBusy(true);setStatus('Buscando empresas...');setPageNo(1);const r=await fetch('/api/v2/scrape',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category,city,state,max_leads:all?null:Number(max),persist:save,webhook:false,worker_count:2,reviews_mode:'summary'})});const j=await r.json();setJob(j.job_id);setBusy(false);setStatus('Coletando informações...');};
 const cancel=async()=>{if(job)await fetch('/api/v2/jobs/'+job+'/cancel',{method:'POST'});setStatus('Busca cancelada')};
 const cols=useMemo<ColumnDef<Lead>[]>(()=>[{accessorKey:'place_name',header:'Empresa',cell:({row})=><div className="company"><strong>{text(row.original.place_name)}</strong><small>{text(row.original.observed_category)}</small></div>},{id:'rating',accessorKey:'total_score',header:'Avaliação',cell:({row})=><span>★ {text(row.original.total_score)}<small>{text(row.original.reviews_count)} avaliações</small></span>},{accessorKey:'address',header:'Endereço',cell:({getValue})=>text(getValue())},{id:'contact',header:'Contato',cell:({row})=><div>{row.original.whatsapp||row.original.phone_raw?<span>{row.original.whatsapp?'WhatsApp: '+row.original.whatsapp:row.original.phone_raw}</span>:<span>—</span>}</div>},{accessorKey:'website',header:'Site',cell:({getValue})=><Link href={getValue()} label="Abrir site"/>},{id:'social',header:'Redes',cell:({row})=><div className="icons">{row.original.instagram?.map(x=><Link key={x} href={x} label={<Instagram size={16}/>}/>)}{row.original.facebook?.map(x=><Link key={x} href={x} label={<Facebook size={16}/>}/>)}{row.original.linkedin?.map(x=><Link key={x} href={x} label={<Linkedin size={16}/>}/>)}</div>},{accessorKey:'google_maps_url',header:'Google',cell:({getValue})=><Link href={getValue()} label="Ver perfil"/>},{id:'status',header:'Status',cell:({row})=><span className="badge">{text(row.original.public_stage||'Dados coletados')}</span>}],[]);
 const table=useReactTable({data:page.items,columns:cols,state:{sorting},onSortingChange:setSorting,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel()});
 return <main><header><h1>Buscar empresas</h1><p>Encontre empresas por categoria e localização.</p></header><section className="form"><label>Categoria / Ramo<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Cidade<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>Estado<input value={state} onChange={e=>setState(e.target.value)}/></label><label>Quantidade<input disabled={all} type="number" min="1" value={max} onChange={e=>setMax(e.target.value)}/></label><label className="check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> Todos disponíveis</label><label className="check"><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)}/> Salvar resultados encontrados</label><button onClick={start} disabled={busy}>Iniciar busca</button><button className="secondary" onClick={cancel}>Cancelar busca</button></section><section className="summary"><div><strong>{status}</strong><span>{page.total_items?`${page.total_items} resultados encontrados`:job?'Aguardando resultados...':'Os resultados aparecerão aqui depois que você iniciar uma busca.'}</span></div><label className="search"><Search size={16}/><input placeholder="Buscar nos resultados..." value={query} onChange={e=>{setPageNo(1);setQuery(e.target.value)}}/></label></section>{page.items.length?<><div className="table-wrap"><table><thead>{table.getHeaderGroups().map(h=><tr key={h.id}>{h.headers.map(x=><th key={x.id} onClick={x.column.getCanSort()?x.column.getToggleSortingHandler():undefined}>{flexRender(x.column.columnDef.header,x.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.original.place_identity}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div><nav className="pagination"><button disabled={!page.has_previous} onClick={()=>{setPageNo(pageNo-1);load(pageNo-1)}}><ChevronLeft size={16}/> Anterior</button><div className="page-links">{pageItems(page.page,page.total_pages).map((n,i)=>n==="…"?<span key={i}>…</span>:<button key={n} className={n===page.page?"active":""} onClick={()=>{setPageNo(Number(n));load(Number(n))}}>{n}</button>)}</div><button disabled={!page.has_next} onClick={()=>{setPageNo(pageNo+1);load(pageNo+1)}}>Próxima <ChevronRight size={16}/></button></nav></>:<div className="empty">{job?'Buscando empresas...':'Os resultados aparecerão aqui depois que você iniciar uma busca.'}</div>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
